### ISSUE TITLE
Can you fix the bug that appear con BloodFx?

### ISSUE THREAD

**Issue by SoyPro** [CyberCube-hk/WalkingParticles#1]
There is a bug in your plugin BloodFx.why dont you update?

**Comment by hoyinm14mc** [comment]
What bug?  Have you tried v1.0.2?

**Comment by SoyPro** [comment]
Sorry there isnt any bug,i see it when playera died but now not.i tell you if you there is any bug.well good job.your plugins are great thanks!

**Comment by SoyPro** [comment]
I have a a question.do you make skywarspe?.i see it why dont you put on pocketmine-mp?in plugins?
